name: PyMC
version: '${version}'
main: com.varlaam.pymc.PyMCPlugin
loader: com.varlaam.pymc.PyMCLoader
api-version: '1.21'
description: Commands and events for Paper written in Python 3
author: Varlaam
permissions:
  pymc.admin:
    description: Use /pymc reload [script], /pymc list and /pymc version
    default: op
